/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author madhulikadekate
 */
public class CommunityLoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form CommunityLoginPanel
     */
    public CommunityLoginPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCommunityAdminUsername = new javax.swing.JLabel();
        lblCommunityAdminPassword = new javax.swing.JLabel();
        txtCommunityAdminUsername = new javax.swing.JTextField();
        txtCommunityAdminPassword = new javax.swing.JTextField();
        btnCommunityAdminLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setText("Community Login");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 65, -1, -1));

        lblCommunityAdminUsername.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        lblCommunityAdminUsername.setText("Username:");
        add(lblCommunityAdminUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 155, -1, -1));

        lblCommunityAdminPassword.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        lblCommunityAdminPassword.setText("Password:");
        add(lblCommunityAdminPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 204, -1, -1));
        add(txtCommunityAdminUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 152, 148, -1));
        add(txtCommunityAdminPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 201, 148, -1));

        btnCommunityAdminLogin.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        btnCommunityAdminLogin.setText("Login");
        btnCommunityAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommunityAdminLoginActionPerformed(evt);
            }
        });
        add(btnCommunityAdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 285, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/IMG6.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCommunityAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommunityAdminLoginActionPerformed
        // TODO add your handling code here:
        String username = txtCommunityAdminUsername.getText();
        String password = txtCommunityAdminPassword.getText();
        if(username.equals("cadmin") && password.equals("12345")){
            
        }
    }//GEN-LAST:event_btnCommunityAdminLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCommunityAdminLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCommunityAdminPassword;
    private javax.swing.JLabel lblCommunityAdminUsername;
    private javax.swing.JTextField txtCommunityAdminPassword;
    private javax.swing.JTextField txtCommunityAdminUsername;
    // End of variables declaration//GEN-END:variables
}
