/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author madhulikadekate
 */
public class DoctorPanelHome extends javax.swing.JPanel {

    /**
     * Creates new form DoctorPanelHome
     */
    public DoctorPanelHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPaneDoctorPanel = new javax.swing.JSplitPane();
        controlPanelDoctor = new javax.swing.JPanel();
        btnCreateEncounter = new javax.swing.JButton();
        btnViewEncounter = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        viewPanelDoctor = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jSplitPaneDoctorPanel.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        controlPanelDoctor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreateEncounter.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        btnCreateEncounter.setText("Create Encounter");
        btnCreateEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEncounterActionPerformed(evt);
            }
        });
        controlPanelDoctor.add(btnCreateEncounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 38, -1, -1));

        btnViewEncounter.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        btnViewEncounter.setText("View Encounter");
        controlPanelDoctor.add(btnViewEncounter, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 38, -1, -1));

        jButton1.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jButton1.setText("Create Vital Signs");
        controlPanelDoctor.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 38, -1, -1));

        jButton2.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jButton2.setText("View Vital Signs");
        controlPanelDoctor.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 38, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/IMG6.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        controlPanelDoctor.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSplitPaneDoctorPanel.setLeftComponent(controlPanelDoctor);

        viewPanelDoctor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/IMG6.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        viewPanelDoctor.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSplitPaneDoctorPanel.setRightComponent(viewPanelDoctor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 882, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jSplitPaneDoctorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jSplitPaneDoctorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEncounterActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnCreateEncounterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateEncounter;
    private javax.swing.JButton btnViewEncounter;
    private javax.swing.JPanel controlPanelDoctor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSplitPane jSplitPaneDoctorPanel;
    private javax.swing.JPanel viewPanelDoctor;
    // End of variables declaration//GEN-END:variables
}
