/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import model.SystemAdmin;

/**
 *
 * @author madhulikadekate
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    SystemAdmin sysAdmin;
    public HomePage() {
        initComponents();
        sysAdmin = new SystemAdmin();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPaneMainPage = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        btnDoctor = new javax.swing.JButton();
        btnCommunityAdmin = new javax.swing.JButton();
        btnSystemAdmin = new javax.swing.JButton();
        btnPatient = new javax.swing.JButton();
        btnHospitalAdmin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        viewPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        controlPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDoctor.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        btnDoctor.setText("Doctor");
        btnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorActionPerformed(evt);
            }
        });
        controlPanel.add(btnDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 175, 137, -1));

        btnCommunityAdmin.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        btnCommunityAdmin.setText("Community Admin");
        btnCommunityAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommunityAdminActionPerformed(evt);
            }
        });
        controlPanel.add(btnCommunityAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 104, -1, -1));

        btnSystemAdmin.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        btnSystemAdmin.setText("System Admin");
        btnSystemAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSystemAdminActionPerformed(evt);
            }
        });
        controlPanel.add(btnSystemAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 69, 137, -1));

        btnPatient.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        btnPatient.setText("Patient");
        btnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientActionPerformed(evt);
            }
        });
        controlPanel.add(btnPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 210, 137, -1));

        btnHospitalAdmin.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        btnHospitalAdmin.setText("Hospital Admin");
        btnHospitalAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospitalAdminActionPerformed(evt);
            }
        });
        controlPanel.add(btnHospitalAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 139, 137, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/IMG6.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        controlPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        splitPaneMainPage.setLeftComponent(controlPanel);

        viewPanel.setName("viewPanel"); // NOI18N
        viewPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        splitPaneMainPage.setRightComponent(viewPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPaneMainPage)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPaneMainPage)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCommunityAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommunityAdminActionPerformed
        // TODO add your handling code here:
        CommunityAdminPanel commadmin = new CommunityAdminPanel(sysAdmin);
        splitPaneMainPage.setRightComponent(commadmin);
        
        
    }//GEN-LAST:event_btnCommunityAdminActionPerformed

    private void btnSystemAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSystemAdminActionPerformed
        // TODO add your handling code here:
        
        SystemAdminPanel sysAdminPane = new SystemAdminPanel(sysAdmin);
        splitPaneMainPage.setRightComponent(sysAdminPane);
        
        
        
        
    }//GEN-LAST:event_btnSystemAdminActionPerformed

    private void btnHospitalAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospitalAdminActionPerformed
        // TODO add your handling code here:
        HospitalAdminPanel hospitalAdmin = new HospitalAdminPanel(sysAdmin);
        splitPaneMainPage.setRightComponent(hospitalAdmin);
    }//GEN-LAST:event_btnHospitalAdminActionPerformed

    private void btnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorActionPerformed
        // TODO add your handling code here:
        DoctorPanel doctorPanel = new DoctorPanel(sysAdmin);
        splitPaneMainPage.setRightComponent(doctorPanel);
        
    }//GEN-LAST:event_btnDoctorActionPerformed

    private void btnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientActionPerformed
        // TODO add your handling code here:
        PatientPanel patientPanel = new PatientPanel(sysAdmin);
        splitPaneMainPage.setRightComponent(patientPanel);
        
    }//GEN-LAST:event_btnPatientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCommunityAdmin;
    private javax.swing.JButton btnDoctor;
    private javax.swing.JButton btnHospitalAdmin;
    private javax.swing.JButton btnPatient;
    private javax.swing.JButton btnSystemAdmin;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane splitPaneMainPage;
    private javax.swing.JPanel viewPanel;
    // End of variables declaration//GEN-END:variables
}
