/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Data;
import model.Product;

/**
 *
 * @author madhulikadekate
 */
public class DataJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DataJPanel
     */
    Data history;
    
    public DataJPanel(Data history) {
        initComponents();
        
        this.history = history;
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        IbIempId = new javax.swing.JLabel();
        txtempId = new javax.swing.JTextField();
        IbIage = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        IbIgender = new javax.swing.JLabel();
        txtgender = new javax.swing.JTextField();
        IbIdate = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        IbIlevel = new javax.swing.JLabel();
        txtlevel = new javax.swing.JTextField();
        IbIteam = new javax.swing.JLabel();
        txtteam = new javax.swing.JTextField();
        IbIposition = new javax.swing.JLabel();
        txtposition = new javax.swing.JTextField();
        IbInumber = new javax.swing.JLabel();
        txtnumber = new javax.swing.JTextField();
        IbIemail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        IbIname = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        IbIsearch = new javax.swing.JLabel();

        Title.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Employee Database");
        Title.setToolTipText("");

        tblData.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Empolyee ID", "Position Title"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblDataMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        btnDelete.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnView.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        IbIempId.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        IbIempId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IbIempId.setText("Employee ID:");

        txtempId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtempIdActionPerformed(evt);
            }
        });

        IbIage.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        IbIage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IbIage.setText("Age:");

        txtage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtageActionPerformed(evt);
            }
        });

        IbIgender.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        IbIgender.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IbIgender.setText("Gender:");

        txtgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgenderActionPerformed(evt);
            }
        });

        IbIdate.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        IbIdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IbIdate.setText("Start Date:");

        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });

        IbIlevel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        IbIlevel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IbIlevel.setText("Level:");

        txtlevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlevelActionPerformed(evt);
            }
        });

        IbIteam.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        IbIteam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IbIteam.setText("Team:");

        txtteam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtteamActionPerformed(evt);
            }
        });

        IbIposition.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        IbIposition.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IbIposition.setText("Position Title:");

        txtposition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpositionActionPerformed(evt);
            }
        });

        IbInumber.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        IbInumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IbInumber.setText("Cell Number:");

        txtnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumberActionPerformed(evt);
            }
        });

        IbIemail.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        IbIemail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IbIemail.setText("Email:");

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        IbIname.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        IbIname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IbIname.setText("Name:");

        btnUpdate.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        IbIsearch.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        IbIsearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IbIsearch.setText("Search:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IbIdate, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(IbIgender, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(IbIage, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(IbIempId, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(IbIname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(IbIsearch, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtsearch, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtdate, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtgender, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtage, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtempId, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(IbIemail)
                                    .addComponent(IbInumber)
                                    .addComponent(IbIposition)
                                    .addComponent(IbIteam)
                                    .addComponent(IbIlevel))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtnumber, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtposition, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtteam, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtlevel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnView)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnView)
                    .addComponent(btnUpdate)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IbIsearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IbIlevel)
                            .addComponent(txtlevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IbIteam)
                            .addComponent(txtteam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IbIposition)
                            .addComponent(txtposition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IbInumber)
                            .addComponent(txtnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IbIemail)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IbIname)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IbIempId)
                            .addComponent(txtempId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IbIage)
                            .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IbIgender)
                            .addComponent(txtgender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IbIdate)
                            .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblData.getSelectedRow();
        if (selectedRowIndex<0){
            
            JOptionPane.showMessageDialog(this, "Please select an entry to view empoyee database.");
            return;
            
        }
          DefaultTableModel model = (DefaultTableModel) tblData.getModel();
          Product selectedProduct = (Product) model.getValueAt(selectedRowIndex, 0);
          
          txtname.setText(String.valueOf(selectedProduct.getName()));
          txtempId.setText(String.valueOf(selectedProduct.getEmpId()));
          txtage.setText(String.valueOf(selectedProduct.getAge()));
          txtgender.setText(String.valueOf(selectedProduct.getGender()));
          txtdate.setText(String.valueOf(selectedProduct.getsDate()));
          txtlevel.setText(String.valueOf(selectedProduct.getLevel()));
          txtteam.setText(String.valueOf(selectedProduct.gettInfo()));
          txtposition.setText(String.valueOf(selectedProduct.getpTitle()));
          txtnumber.setText(String.valueOf(selectedProduct.getNum()));
          txtemail.setText(String.valueOf(selectedProduct.getEmail()));
          
    }//GEN-LAST:event_btnViewActionPerformed

    private void txtempIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtempIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtempIdActionPerformed

    private void txtageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtageActionPerformed

    private void txtgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgenderActionPerformed

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateActionPerformed

    private void txtlevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlevelActionPerformed

    private void txtteamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtteamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtteamActionPerformed

    private void txtpositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpositionActionPerformed

    private void txtnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumberActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblData.getSelectedRow();
        if (selectedRowIndex<0){
            
            JOptionPane.showMessageDialog(this, "Please select an entry to delete.");
            return;
            
        }
          DefaultTableModel model = (DefaultTableModel) tblData.getModel();
          Product selectedProduct = (Product) model.getValueAt(selectedRowIndex, 0);
          
          history.deleteProduct(selectedProduct);
          JOptionPane.showMessageDialog(this, "Employee data deleted.");
          
          populateTable();
          
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) tblData.getModel();
         if(tblData.getSelectedRowCount() == 1) {
             
        String name = txtname.getText();
        String empId = txtempId.getText();
        String pTitle = txtposition.getText();
        
        model.setValueAt(name, tblData.getSelectedRow(), 0);
        model.setValueAt(empId, tblData.getSelectedRow(), 1);
        model.setValueAt(pTitle, tblData.getSelectedRow(), 2);

        
        JOptionPane.showMessageDialog(this, "Updated Successfully.");
        
        } else{
             if(tblData.getRowCount() == 0){
               JOptionPane.showMessageDialog(this, "Table is Empty.");  
             }else{
                 JOptionPane.showMessageDialog(this, "Select Single Row for Update."); 
             }
         }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void tblDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDataMouseEntered

    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblData.getModel();
        
        String tblName = model.getValueAt(tblData.getSelectedRow(), 0).toString();
        String tblEmpId = model.getValueAt(tblData.getSelectedRow(), 1).toString();
        String tblPosition = model.getValueAt(tblData.getSelectedRow(), 2).toString();
        
        txtname.setText(tblName);
        txtempId.setText(tblEmpId);
        txtposition.setText(tblPosition);
    
        
    }//GEN-LAST:event_tblDataMouseClicked

    private void txtsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyPressed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblData.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        tblData.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txtsearch.getText().trim()));
        
 
    }//GEN-LAST:event_txtsearchKeyPressed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IbIage;
    private javax.swing.JLabel IbIdate;
    private javax.swing.JLabel IbIemail;
    private javax.swing.JLabel IbIempId;
    private javax.swing.JLabel IbIgender;
    private javax.swing.JLabel IbIlevel;
    private javax.swing.JLabel IbIname;
    private javax.swing.JLabel IbInumber;
    private javax.swing.JLabel IbIposition;
    private javax.swing.JLabel IbIsearch;
    private javax.swing.JLabel IbIteam;
    private javax.swing.JLabel Title;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtempId;
    private javax.swing.JTextField txtgender;
    private javax.swing.JTextField txtlevel;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnumber;
    private javax.swing.JTextField txtposition;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txtteam;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
    DefaultTableModel model = (DefaultTableModel) tblData.getModel();
    model.setRowCount(0);
    
    for (Product vs : history.getHistory()){
        Object[] row = new Object[3];
        row[0] = vs;
        row[1] = vs.getEmpId();
        row[2] = vs.getpTitle();
        
        model.addRow(row);
        
    }
    
    }
    
}
